### ISSUE TITLE
Run a user test

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Sample-Creator#17]
Run a user test with Justin, making sure that he can use the workflow from his machine without your help.

**Comment by dashaveraksa** [comment]
Completed by Justin on August 12, everything at that point seemed to be functioning. One of his notes was that the uploaded plasmids do not show any annotations which would be a great feature to have in the future (instead of showing black square brackets).

**Comment by jakebeal** [comment]
If they're showing unknown annotations (i.e., the brackets), that likely indicates an issue in the annotations that are getting exported from Benchling by @jhletendre.  Can we get a sample file to look at?

**Comment by dashaveraksa** [comment]
Here is an example:
https://synbiohub.org/user/dveraksa/ExampleProject/JHT14_codename_5F0S/1/b5bf6fba366f9823de0e1de7c8109f34177d164c/share

By Benchling annotations do you mean the ones that are created using Ben's tool? If so I do not think they have been added to SynBioHub yet and the plasmid definitions are not in the LCP Dictionary which is why they are showing unknown annotations.

**Comment by jakebeal** [comment]
Oh, right --- it's because nothing's been uploaded to SynBioHub to connect the sequences to.
